name: Release

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      version_file:
        required: true
        type: string

jobs:
  release:
    uses: clouddrove-sandbox/reusable-workflow/.github/workflows/release.yml@master # Reference to your reusable workflow
    with:
      branch: master # Specify the branch to merge into
      version_file: VERSION # Specify the version file (like `VERSION` file)
