name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove-sandbox/resource-group-workflow/.github/workflows/workflow.yml@master
    with:
      target_branch: master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
