name: Call Release on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - master  # or your default branch

jobs:
  call-release-workflow:
    if: github.event.pull_request.merged == true
    uses: clouddrove-sandbox/resource-group-workflow/.github/workflows/workflow.yaml@master
    with:
      target_branch: 'master'
      version_file: 'VERSION'   # Optional, defaults to 'VERSION' if omitted
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
