name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove-sandbox/resource-group-workflow/.github/workflows/tf-scan.yml@master
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'
